# Generated by Django 2.0.2 on 2018-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
