# Generated by Django 2.0.2 on 2018-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_dib_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='receiver',
            field=models.CharField(default='000', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='want_dibs',
            field=models.BooleanField(default=False),
        ),
    ]
