# Generated by Django 2.0.2 on 2018-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20180203_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='image',
            field=models.ImageField(default='noo', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dib',
            name='receiver',
            field=models.CharField(default='empty', max_length=12),
        ),
    ]
