# Generated by Django 2.0.2 on 2018-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20180203_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='imageurl',
            field=models.URLField(default='empty'),
            preserve_default=False,
        ),
    ]
