# Generated by Django 2.0.2 on 2018-02-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_dib_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dib',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
